; (c) 2020 rxi

(= title "Hello World!")
(= scale 7)
(= width 16)
(= height 6)
(= n 0)


(= step (fn ()
    ; clear screen
    (fill 0 0 width height " ")

    ; draw "Hello World!" text
    (color 1)
    ;(put 6 7 "Hello")
    (put 2 2 "Hello")
    (color 2)
    ;(put 12 7 "World!")
    (put 8 2 "World!")

    ; draw divider
    (color 14)
    (put 2 3 "............")
    (color 1)
    (put (+ 2 (% n 12)) 3 ".")

    ; update step count
    (= n (+ n 1))
))
